// After 9 — "How Well Do You Really Know Me?"
// 120 questions across 4 escalating rounds (30 each).
const AFTER9_GAME = {
  title: "How Well Do You Really Know Me?",
  tagline: "Things get interesting after 9.",
  rounds: [
    {
      id: 1,
      name: "You Should Know This",
      intro: "Warm-up round. Light, easy, a little funny — the stuff you should already know about each other.",
      questions: [
        "What's my go-to order at a coffee shop?",
        "What's the one show I'll rewatch no matter what?",
        "Am I a morning person or a night owl — really?",
        "What's currently my most-used emoji?",
        "What did I want to be when I was a kid?",
        "What's my comfort food when I've had a rough day?",
        "What's on my phone's lock screen right now?",
        "What's my biggest pet peeve that I complain about most?",
        "What's my karaoke song, whether I admit it or not?",
        "What's the last thing I said I'd “do tomorrow” and still haven't?",
        "What's my dream vacation, no budget involved?",
        "What's a food I claim to hate but have never actually tried?",
        "What's the first thing I do when I get home?",
        "What's my go-to excuse to get out of something I don't want to do?",
        "What's a song that instantly puts me in a good mood?",
        "What side of the bed do I sleep on, and would I ever switch?",
        "What's the last thing I Googled that I probably wouldn't want read out loud?",
        "What's my “I'm getting sick” tell before I even notice it myself?",
        "What's a skill I wish I had but have never actually tried to learn?",
        "What's my order if we're splitting a pizza and I'm picking the toppings?",
        "What's the one household task I will avoid for as long as humanly possible?",
        "What's my go-to small talk topic with strangers?",
        "What's something I always have in my bag or pockets?",
        "What's a movie I can quote almost word for word?",
        "What's my honest opinion on mornings before coffee?",
        "What's the weirdest thing I've ever admitted to being afraid of?",
        "What's my go-to order when I'm too tired to decide anything?",
        "What's a compliment I give other people all the time?",
        "What's something I do when I think no one's watching?",
        "What's one thing about me that surprised you in the first month we knew each other?"
      ]
    },
    {
      id: 2,
      name: "Be Honest",
      intro: "Getting warmer. This round is about us — how you love, how you're loved, and what usually goes unsaid.",
      questions: [
        "What's a moment you knew this was becoming serious?",
        "What do you think is my best quality — the one you'd brag about?",
        "What's something I do that you don't think I realize means a lot to you?",
        "What's a memory of us you find yourself replaying?",
        "When do you feel most loved by me?",
        "What's something you've forgiven me for that we never really talked through?",
        "What's a fear you've had about us that you haven't said out loud?",
        "What do you think I underestimate about myself?",
        "What's a compliment you wish I gave you more often?",
        "What's something about how I show love that took you time to understand?",
        "What's a moment you felt completely seen by me?",
        "What do you think is the hardest part of loving someone like me?",
        "What's something small I do that you'd genuinely miss if it stopped?",
        "What's a version of yourself you feel like I bring out?",
        "What's something you've never told me about how you felt when we met?",
        "What do you think I need to hear more, even if I don't ask for it?",
        "What's a moment you felt closest to me, even without saying anything?",
        "What's something you think I do better than I give myself credit for?",
        "What's a fight or hard moment that actually made us stronger?",
        "What do you think has changed most about how you love me since we started?",
        "What's something you're proud of us for getting through together?",
        "What's a way I've supported you that you don't think I know mattered?",
        "What do you think I'm most afraid of losing?",
        "What's a habit of mine that used to bother you and now you'd miss?",
        "What's something you wish we talked about more often?",
        "What's a moment you felt like a team, no explanation needed?",
        "What do you think I'd say is my biggest fear about us?",
        "What's a way you think I've grown since we've been together?",
        "What's something you've never had to ask me for, because I just do it?",
        "If you had to describe what “us” feels like in one sentence, what would it be?"
      ]
    },
    {
      id: 3,
      name: "Don't Overthink It",
      intro: "No overthinking, no rehearsed answers — first instinct only. Attraction, chemistry, and a few things you've never said out loud.",
      questions: [
        "What's the first thing you noticed about me — physically, before anything else?",
        "When do you find me most attractive: right when I wake up, dressed up, or mid-laugh?",
        "Has there ever been someone in my orbit you were a little jealous of?",
        "What's a moment the tension between us was impossible to ignore?",
        "What's something I do without realizing it that you find irresistible?",
        "Is there an outfit of mine you secretly hope makes a comeback?",
        "What's a version of me — earlier in us — you sometimes miss?",
        "What's a secret you've kept just to avoid an argument?",
        "Who would you trust me around the least, honestly?",
        "What's the boldest thing you've thought about saying to me but held back?",
        "Do you still think about our first kiss?",
        "What's something about the way I talk to you that gets to you every time?",
        "What's a moment you caught yourself staring at me and hoped I didn't notice?",
        "What's something I do that you'd never admit turns you on a little?",
        "Has jealousy ever made you realize how much you actually wanted this?",
        "What's a text or message from me you've reread more than once?",
        "What's something about my confidence — or lack of it — that pulls you in?",
        "Is there a memory of us that still makes your stomach flip a little?",
        "What's a compliment about me you've said to other people but not to my face?",
        "What's the most honest answer to: do you think about me during the day?",
        "What's something I wear — or don't wear — that you have strong opinions about?",
        "What's a moment you felt genuinely competitive for my attention?",
        "What's the real reason you remember our first real conversation so clearly?",
        "What's something small — a look, a laugh, a moment — that hooked you early on?",
        "Is there a “what if” from before us you still think about occasionally?",
        "What's something about my personality that's more attractive to you than my looks?",
        "What's a moment you felt proud to be the one standing next to me?",
        "What's the closest you've come to telling me something you were nervous to say?",
        "What's something about tonight, specifically, that you're curious about?",
        "On a scale that has nothing to do with looks, how would you rate our chemistry right now — and why?"
      ]
    },
    {
      id: 4,
      name: "After 9",
      intro: "You've made it. This is the last round — and it's exactly what it sounds like. Answer honestly, skip freely, and see where it goes.",
      questions: [
        "What's one thing you've always wanted to try with me but haven't brought up?",
        "If tonight had zero interruptions and zero rules, what's the first thing you'd want to happen?",
        "What's a compliment about my body you don't say often enough?",
        "Where's somewhere unexpected you'd want to be kissed right now?",
        "What's a memory of us that still gets you a little worked up when you think about it?",
        "If you could set the mood for exactly how tonight goes, what's the first move?",
        "What's something about the way I look at you that makes it hard to concentrate?",
        "What's one thing you find yourself thinking about us that you've never said out loud?",
        "What's your honest answer: are you thinking about tonight right now, or already?",
        "What's a detail about me — voice, hands, whatever — that gets to you more than you'd admit?",
        "If we skipped the rest of this game right now, what would you want to do instead?",
        "What's something you've imagined about us that felt a little too bold to say out loud?",
        "Rate our chemistry tonight, 1 to 10 — and tell me exactly what's earning that number.",
        "What's one thing I could whisper right now that would completely derail this game?",
        "What's the most honest answer to: what do you want from me after this question?",
        "What's a “someday” fantasy involving us you've never actually said out loud?",
        "What's something about tonight specifically that's got your attention more than usual?",
        "If I asked you to describe exactly how you want the rest of the night to go, what would you say?",
        "What's a compliment you've been holding back because it felt like too much?",
        "What's the boldest thing you'd do right now if I said “no rules for the next hour”?",
        "What's a memory from tonight already that you know you'll be thinking about later?",
        "What's something you want me to do the second this game ends?",
        "What's the truest answer to: are you more interested in finishing this round, or finishing it later?",
        "What's one thing about being with me tonight that feels different from any other night?",
        "If this were the last question of the night, what would you want to happen next?",
        "What's something you've wanted to say all night but kept saving for exactly this round?",
        "What's a version of tonight you've already been picturing before we even got here?",
        "What's the one thing standing between us and skipping straight to dessert?",
        "Last question, no overthinking: in one sentence, how do you want tonight to end?",
        "Set the tone for the rest of the night in five words or less. Go."
      ]
    }
  ]
};
